version: '3'

services:
    rdb:
        image: mysql:8.0.15
        command: ['--default-authentication-plugin=mysql_native_password']
        volumes:
            - '../../data/rdb:/var/lib/mysql:rw'
        environment:
            - 'MYSQL_DATABASE=duo'
            - 'MYSQL_USER=root'
            - 'MYSQL_PASSWORD=root'
            - 'MYSQL_ROOT_PASSWORD=root'
            - 'TZ=Asia/Seoul'
        ports:
            - '33061:3306'

        # redis
    redis:
        image: redis:5.0.4-alpine
        volumes:
            - '../../data/redis:/data:rw'
        environment:
            - 'TZ=Asia/Seoul'
        ports:
            - '63791:6379'
